# -*- coding: utf-8 -*-
"""3_VAR_COMB_codeFinal_230809.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1okdJlzDYzK4EtLjr-OxJ1ZHOkYUUjBkM
"""

from itertools import product
from itertools import permutations
from itertools import combinations

items = ['인적사고','공종','사고객체','작업프로세스','사고원인']
from itertools import permutations
list(permutations(items,2))

list(permutations(items,3))

list(permutations(items,4))

list(permutations(items,5))