# -*- coding: utf-8 -*-
"""5_SEV_SCEN_codeFinal.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gGpo8CTql3fuAw8LvlCF-K3VBc9JI2xP
"""

# Google Drive 마운트
from google.colab import drive
drive.mount('/content/drive')

data = {
    'conType_L': [],
    'accident_L': [],
    'process_L': [],
    'accObject_L': [],
    'cause_L': []
}

import csv

# 파일 경로 설정
file_path = '/content/drive/MyDrive/Data/strList_230830.csv'

with open(file_path, 'r', encoding='cp949') as csv_file:
    csv_reader = csv.DictReader(csv_file)
    for row in csv_reader:
      if row['conType']:
        data['conType_L'].append(row['conType'])
      if row['accident']:
        data['accident_L'].append(row['accident'])
      if row['process']:
        data['process_L'].append(row['process'])
      if row['accObject']:
        data['accObject_L'].append(row['accObject'])
      if row['cause']:
        data['cause_L'].append(row['cause'])

print(data['conType_L'])
print(data['accident_L'])
print(data['process_L'])
print(data['accObject_L'])
print(data['cause_L'])

import pandas as pd

file_path_2 = '/content/drive/MyDrive/Data/strength_anlaysis_filtered_230830.csv'
df = pd.read_csv(file_path_2, encoding='cp949') # df는 사고사례 전체 데이터

print(df.columns)

"""**Merging all cases**"""

import glob

# 병합할 CSV 파일들의 경로 리스트를 가져옴
csv_files = glob.glob('/content/drive/MyDrive/Data/strScore/*.csv')  # 병합할 CSV 파일들의 경로 지정

# CSV 파일들을 순회하며 데이터프레임으로 불러온 후 리스트에 추가
dfs = []
for csv_file in csv_files:
    df = pd.read_csv(csv_file, encoding='utf-8')  # 필요한 인코딩으로 변경
    dfs.append(df)

# 여러 데이터프레임을 하나의 데이터프레임으로 병합
merged_df = pd.concat(dfs, ignore_index=True)

# 병합된 데이터프레임을 CSV 파일로 저장
merged_csv_file = '/content/drive/MyDrive/Data/strScore/strScore_merged.csv'  # 저장할 병합된 CSV 파일의 이름
merged_df.to_csv(merged_csv_file, index=False, encoding='utf-8-sig')  # 필요한 인코딩으로 변경

merged_df

