# -*- coding: utf-8 -*-
"""6_RISK_codeFinal

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KD48a6AeH2LVMEVrtV0_iwEIWEk7Eu7b
"""

# csv2 파일 순회하며 csv1과 매칭
for index, row in csv2_df.iterrows():
    conType = row['conType']
    accident = row['accident']
    process = row['process']
    accObject = row['accObject']
    cause = row['cause']

    # csv1_selected_vars에서 조건에 해당하는 행 찾기 & 매칭된 데이터가 있는 경우에만 값을 할당
    # case 1: conType + accident
    matching_row = csv1_selected_vars[(csv1_selected_vars['conType'] == conType) & (csv1_selected_vars['accident'] == accident)]

    if not matching_row.empty:
        csv2_df.at[index, 'frq1'] = matching_row['frqScore'].values[0]
        csv2_df.at[index, 'str1'] = matching_row['strScore'].values[0]


    # case 2: accident + process
    matching_row = csv1_selected_vars[(csv1_selected_vars['accident'] == accident) & (csv1_selected_vars['process'] == process)]

    if not matching_row.empty:
        csv2_df.at[index, 'frq2'] = matching_row['frqScore'].values[0]
        csv2_df.at[index, 'str2'] = matching_row['strScore'].values[0]


    # case 3: process + accObject
    matching_row = csv1_selected_vars[(csv1_selected_vars['process'] == process) & (csv1_selected_vars['accObject'] == accObject)]

    if not matching_row.empty:
        csv2_df.at[index, 'frq3'] = matching_row['frqScore'].values[0]
        csv2_df.at[index, 'str3'] = matching_row['strScore'].values[0]


    # case 4: accObject + cause
    matching_row = csv1_selected_vars[(csv1_selected_vars['accObject'] == accObject) & (csv1_selected_vars['cause'] == cause)]

    if not matching_row.empty:
        csv2_df.at[index, 'frq4'] = matching_row['frqScore'].values[0]
        csv2_df.at[index, 'str4'] = matching_row['strScore'].values[0]